"""empty message

Revision ID: 1162f603e5c8
Revises: 2832ccb3734e
Create Date: 2018-09-20 10:58:52.659355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1162f603e5c8'
down_revision = '2832ccb3734e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtime', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showtime', 'count')
    # ### end Alembic commands ###
