"""empty message

Revision ID: 2832ccb3734e
Revises: 
Create Date: 2018-09-18 17:35:35.836146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2832ccb3734e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('showtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('theater_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['theater_id'], ['theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtime')
    op.drop_table('theater')
    op.drop_table('film')
    # ### end Alembic commands ###
